# Generated by Django 4.1.9 on 2023-11-24 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import propylon_document_manager.utils.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_name", models.CharField(max_length=512, verbose_name="file_name")),
                ("file_version", models.IntegerField(default=0, verbose_name="file_version")),
                ("file_size", models.CharField(max_length=20, verbose_name="file_size")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("Docs", "Docs"),
                            ("Images", "Images"),
                            ("Videos", "Videos"),
                            ("Procedures", "Procedures"),
                            ("Others", "Others"),
                        ],
                        default="others",
                        max_length=15,
                        verbose_name="file_type",
                    ),
                ),
                ("file_url", models.CharField(max_length=512, verbose_name="file_url")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="create_time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="update_time")),
                ("deleted_at", models.DateTimeField(auto_now=True, verbose_name="delete_time")),
                (
                    "file_uuid",
                    models.UUIDField(
                        default=propylon_document_manager.utils.utils.get_uuid, unique=True, verbose_name="file_uuid"
                    ),
                ),
                ("file_name_hash", models.CharField(max_length=32, verbose_name="file_uuid")),
                ("file_desc", models.CharField(default="", max_length=512, verbose_name="file_desc")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
