# Generated by Django 4.1.9 on 2023-11-22 19:25

from django.db import migrations, models
import propylon_document_manager.utils.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_name", models.CharField(max_length=512, verbose_name="file_name")),
                ("file_version", models.IntegerField(default=0, verbose_name="file_version")),
                ("file_size", models.CharField(max_length=20, verbose_name="file_size")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("docs", "docs"),
                            ("imgs", "imgs"),
                            ("videos", "videos"),
                            ("Procedures", "Procedures"),
                            ("others", "others"),
                        ],
                        default="others",
                        max_length=15,
                        verbose_name="file_type",
                    ),
                ),
                ("file_url", models.CharField(max_length=512, verbose_name="file_url")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="create_time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="update_time")),
                ("deleted_at", models.DateTimeField(auto_now=True, verbose_name="delete_time")),
                (
                    "file_uuid",
                    models.UUIDField(
                        default=propylon_document_manager.utils.utils.get_uuid, unique=True, verbose_name="file_uuid"
                    ),
                ),
                ("file_name_hash", models.CharField(max_length=32, verbose_name="file_uuid")),
            ],
        ),
    ]
