# Generated by Django 4.1.9 on 2023-11-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="file_desc",
            field=models.CharField(default="", max_length=512, verbose_name="file_desc"),
        ),
    ]
